### ISSUE TITLE
Update title of vignette Previously Used Methods for Estimating Survival, Recruitment, and Population Growth

### ISSUE THREAD

**Issue by aylapear** [poissonconsulting/bbouretro#41]
Suggestion to update to says "Frequentist methods" instead of "Previously Used methods".

**Comment by aylapear** [comment]
Is the Lefkovich matrix a frequentist method? If not then not sure if that title encompasses all the methods listed in the doc. Agreed that "Previously Used" could be a better phrase

**Comment by aylapear** [comment]
@joethorley

**Comment by joethorley** [comment]
I think go with Classical Methods
