### ISSUE TITLE
Check reference on log vs logit scale for equation in vignette

### ISSUE THREAD

**Issue by aylapear** [poissonconsulting/bbouretro#42]
>The sampling distribution of S^∗ is quite skewed therefore the 95% Wald confidence interval (Millar 2011) is calculated on the log scale (before being back-transformed).
>
> log(S^∗)±1.96 S^∗−1 SE(S^∗)

Need to confirm if this should be log or logit scale.

**Comment by aylapear** [comment]
@joethorley

**Comment by joethorley** [comment]
This is truly the natural log.
<img width="337" alt="Screenshot 2024-04-25 at 16 38 00" src="https://github.com/poissonconsulting/bbouretro/assets/613671/528e597f-ba1a-4d3a-9415-5eeea488a0fa">

**Comment by aylapear** [comment]
Confirmed it is log and closed off, method used in retro is not this one.
