### ISSUE TITLE
Isn't it possible to get calf cow ratio from output of `bbr_recruitment()` function?

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/bbouretro#51]

**Comment by sebdalgarno** [comment]
good question - I was thinking it would be tricky after the se/lower/upper created...but didn't think about it too much 
here is the output of bbr_recruitment

<img width="789" alt="image" src="https://github.com/poissonconsulting/bbouretro/assets/15878432/3fe0773b-de0f-455b-af53-b8252a83d725">

**Comment by joethorley** [comment]
Yes I've just done a PR to have functions to allow conversion between the calf cow ratio and female rec. here

https://github.com/poissonconsulting/bbouretro/pull/52
